services:
  app:
    image: ghcr.io/letsdrinksometea/semnia:main
    container_name: semnia
    build: .
    restart: unless-stopped
    ports:
      - "3000:8000"
    volumes:
      - data:/data
      - semnia-model-cache:/model-cache
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

  ollama:
    image: ollama/ollama
    container_name: semnia-ollama
    restart: unless-stopped
    volumes:
      - ollama_data:/root/.ollama
    profiles:
      - llm

volumes:
  data:
  semnia-model-cache:
  ollama_data:
